import os

VERIFY_TOKEN = os.getenv("WHATSAPP_WEBHOOK_VERIFICATION_TOKEN")
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
MANAGER_NUMBER = os.getenv("MANAGER_NUMBER", "")
GOOGLE_SHEET_WEBHOOK = os.getenv("GOOGLE_SHEET_WEBHOOK", "")
MIN_DELIVERY_ORDER = 30.00
MIN_PICKUP_ORDER = 10.00
DELIVERY_CHARGE = 4.99
FREE_DELIVERY_THRESHOLD = 50.00
POST_ORDER_WINDOW = 180
LANG_NAMES = {"en": "English", "ar": "Arabic", "hi": "Hindi"}
